### ISSUE TITLE
Problem in loading the trained weights provided.

### ISSUE THREAD

**Issue by nishant34** [tedyhabtegebrial/gvsnet#1]
The following error is there when loading the trained weights:
RuntimeError: Error(s) in loading state_dict for GVSNet:
        Missing key(s) in state_dict: "discriminator.discriminator_0.model0.0.weight", "discriminator.discriminator_0.model0.0.bias", "discriminator.discriminator_0.model1.0.0.weight_orig", "discriminator.discriminator_0.model1.0.0.weight", "discriminator.discriminator_0.model1.0.0.weight_u", "discriminator.discriminator_0.model1.0.0.weight_orig", "discriminator.discriminator_0.model1.0.0.weight_u", "discriminator.discriminator_0.model1.0.0.weight_v", "discriminator.discriminator_0.model2.0.0.weight_orig", "discriminator.discriminator_0.model2.0.0.weight", "discriminator.discriminator_0.model2.0.0.weight_u", "discriminator.discriminator_0.model2.0.0.weight_orig", "discriminator.discriminator_0.model2.0.0.weight_u", "discriminator.discriminator_0.model2.0.0.weight_v", "discriminator.discriminator_0.model3.0.0.weight_orig", "discriminator.discriminator_0.model3.0.0.weight", "discriminator.discriminator_0.model3.0.0.weight_u", "discriminator.discriminator_0.model3.0.0.weight_orig", "discriminator.discriminator_0.model3.0.0.weight_u", "discriminator.discriminator_0.model3.0.0.weight_v", "discriminator.discriminator_0.model4.0.weight", "discriminator.discriminator_0.model4.0.bias", "discriminator.discriminator_1.model0.0.weight", "discriminator.discriminator_1.model0.0.bias", "discriminator.discriminator_1.model1.0.0.weight_orig", "discriminator.discriminator_1.model1.0.0.weight", "discriminator.discriminator_1.model1.0.0.weight_u", "discriminator.discriminator_1.model1.0.0.weight_orig", "discriminator.discriminator_1.model1.0.0.weight_u", "discriminator.discriminator_1.model1.0.0.weight_v", "discriminator.discriminator_1.model2.0.0.weight_orig", "discriminator.discriminator_1.model2.0.0.weight", "discriminator.discriminator_1.model2.0.0.weight_u", "discriminator.discriminator_1.model2.0.0.weight_orig", "discriminator.discriminator_1.model2.0.0.weight_u", "discriminator.discriminator_1.model2.0.0.weight_v", "discriminator.discriminator_1.model3.0.0.weight_orig", "discriminator.discriminator_1.model3.0.0.weight", "discriminator.discriminator_1.model3.0.0.weight_u", "discriminator.discriminator_1.model3.0.0.weight_orig", "discriminator.discriminator_1.model3.0.0.weight_u", "discriminator.discriminator_1.model3.0.0.weight_v", "discriminator.discriminator_1.model4.0.weight", "discriminator.discriminator_1.model4.0.bias", "discriminator.discriminator_2.model0.0.weight", "discriminator.discriminator_2.model0.0.bias", "discriminator.discriminator_2.model1.0.0.weight_orig", "discriminator.discriminator_2.model1.0.0.weight", "discriminator.discriminator_2.model1.0.0.weight_u", "discriminator.discriminator_2.model1.0.0.weight_orig", "discriminator.discriminator_2.model1.0.0.weight_u", "discriminator.discriminator_2.model1.0.0.weight_v", "discriminator.discriminator_2.model2.0.0.weight_orig", "discriminator.discriminator_2.model2.0.0.weight", "discriminator.discriminator_2.model2.0.0.weight_u", "discriminator.discriminator_2.model2.0.0.weight_orig", "discriminator.discriminator_2.model2.0.0.weight_u", "discriminator.discriminator_2.model2.0.0.weight_v", "discriminator.discriminator_2.model3.0.0.weight_orig", "discriminator.discriminator_2.model3.0.0.weight", "discriminator.discriminator_2.model3.0.0.weight_u", "discriminator.discriminator_2.model3.0.0.weight_orig", "discriminator.discriminator_2.model3.0.0.weight_u", "discriminator.discriminator_2.model3.0.0.weight_v", "discriminator.discriminator_2.model4.0.weight", "discriminator.discriminator_2.model4.0.bias", "vgg_loss.vgg.slice1.0.weight", "vgg_loss.vgg.slice1.0.bias", "vgg_loss.vgg.slice2.2.weight", "vgg_loss.vgg.slice2.2.bias", "vgg_loss.vgg.slice2.5.weight", "vgg_loss.vgg.slice2.5.bias", "vgg_loss.vgg.slice3.7.weight", "vgg_loss.vgg.slice3.7.bias", "vgg_loss.vgg.slice3.10.weight", "vgg_loss.vgg.slice3.10.bias", "vgg_loss.vgg.slice4.12.weight", "vgg_loss.vgg.slice4.12.bias", "vgg_loss.vgg.slice4.14.weight", "vgg_loss.vgg.slice4.14.bias", "vgg_loss.vgg.slice4.16.weight", "vgg_loss.vgg.slice4.16.bias", "vgg_loss.vgg.slice4.19.weight", "vgg_loss.vgg.slice4.19.bias", "vgg_loss.vgg.slice5.21.weight", "vgg_loss.vgg.slice5.21.bias", "vgg_loss.vgg.slice5.23.weight", "vgg_loss.vgg.slice5.23.bias", "vgg_loss.vgg.slice5.25.weight", "vgg_loss.vgg.slice5.25.bias", "vgg_loss.vgg.slice5.28.weight", "vgg_loss.vgg.slice5.28.bias".

**Comment by tedyhabtegebrial** [comment]
Hi,

Did this happen in the demo script ?

**Comment by nishant34** [comment]
Hi,

Yes, when I tried to run the demo script after downloading the weights it
showed this error. I checked the keys in the weights state dict which I
downloaded from the drive and discriminator weights doesn't exist in it.

**Comment by tedyhabtegebrial** [comment]
Hi,

Please get the latest commit and try again. Make sure you use the option ```--dataset=carla_samples``` instead of  ```--dataset=carla ```

**Comment by nishant34** [comment]
Yeah it is working fine now. Thanks for the help
